spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: websocket
          uri: lb://websocket-service
          order: 1
          predicates:
            - Path=/websocket-service/**
          filters:
            - RewritePath=/websocket-service/(?<segment>.*),/$\{segment}
server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
