spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:23306
    username: user
    password: test1357
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true