global:
  scrape_interval: 1s

scrape_configs:
  - job_name: "prometheus-grafana-example"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
