### (1) 고양이 alice 추가
POST http://localhost:5999/cat
Content-Type: application/json

{
  "id": 1000,
  "name": "alice"
}

###  (2) 고양이 brooks 추가
POST http://localhost:5999/cat
Content-Type: application/json

{
  "id": 2000,
  "name": "brooks"
}

### (3) 고양이 cadens 추가
POST http://localhost:5999/cat
Content-Type: application/json

{
  "id": 3000,
  "name": "cadens"
}



### (4) 고양이 cadens 추가 (json 으로)
POST http://localhost:5999/cat/json
Content-Type: application/json

{
  "id": 3000,
  "name": "cadens"
}
